CREATE TABLE IF NOT EXISTS applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    company VARCHAR(255) NOT NULL,
    job_role VARCHAR(255) NOT NULL,
    region VARCHAR(64) NOT NULL DEFAULT 'Other',
    status VARCHAR(64) NOT NULL,
    applied_date DATE NOT NULL,
    link VARCHAR(1024),
    notes VARCHAR(2000),
    company_summary VARCHAR(4000),
    country VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE applications ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE applications ADD COLUMN IF NOT EXISTS region VARCHAR(64) NOT NULL DEFAULT 'Other';
ALTER TABLE applications ADD COLUMN IF NOT EXISTS company_summary VARCHAR(4000);
ALTER TABLE applications ADD COLUMN IF NOT EXISTS country VARCHAR(255);
ALTER TABLE applications ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE applications ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

UPDATE applications SET region = 'Other' WHERE region IS NULL;
UPDATE applications SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
UPDATE applications SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_applications_region ON applications(region);
CREATE INDEX IF NOT EXISTS idx_applications_updated_at ON applications(updated_at);
CREATE INDEX IF NOT EXISTS idx_applications_user_id ON applications(user_id);

CREATE TABLE IF NOT EXISTS app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(128) UNIQUE,
    password VARCHAR(256) NOT NULL,
    salt VARCHAR(256) NOT NULL
);

ALTER TABLE app_users ADD COLUMN IF NOT EXISTS email VARCHAR(255);
UPDATE app_users SET email = username WHERE email IS NULL AND username IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_app_users_email ON app_users(email);

CREATE TABLE IF NOT EXISTS documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    application_id BIGINT NULL,
    original_filename VARCHAR(512) NOT NULL,
    object_key VARCHAR(1024) NOT NULL UNIQUE,
    content_type VARCHAR(255) NOT NULL,
    size_bytes BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_documents_application
        FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE SET NULL
);

ALTER TABLE documents ADD COLUMN IF NOT EXISTS user_id BIGINT;
CREATE INDEX IF NOT EXISTS idx_documents_application_id ON documents(application_id);
CREATE INDEX IF NOT EXISTS idx_documents_user_id ON documents(user_id);
